---
title: "Case Landscapes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

SF_TO_POINT_LEAFLET <- function(path, name){
  SF <- st_read(path) %>% 
    suppressWarnings(st_centroid()) %>% 
    st_transform(crs = '+proj=longlat +datum=WGS84') %>% 
    st_coordinates() %>% 
    as.data.frame() %>% 
    dplyr::select(X, Y) %>% 
    mutate(Name = name) %>% 
    group_by(Name) %>% 
    summarise_all(median) %>% 
    ungroup() %>% 
    st_as_sf(coords = c("X", "Y"), crs = '+proj=longlat +datum=WGS84')
  return(SF)
}

library(sf)
library(tidyverse)
library(leaflet)

SHAPES <- list.files(pattern = "shp", path = "CaseLandscapes/", full.names = T)

SHAPES  <- SHAPES[stringr::str_detect(SHAPES, pattern = ".xml", negate = T)]

Areas  <- SHAPES %>% purrr::map(read_sf) %>% purrr::map(~st_transform(.x ,crs = '+proj=longlat +datum=WGS84')) 

Paths <- c("Rewild/Gyttegaard/GIS/Gytteg├еrd hegninger.shp", "Rewild/Husby/Husby_ProjectArea.shp", "Rewild/Husby/Trojborg_ProjectArea.shp", "Rewild/KattrupVildnis/Kattrup_Vildnis_graense_jan2022.shp","Rewild/Mols/MolsRewildingArea_polygon2.shp","Rewild/RyeNoskov/RyeNorskov_Exp_Centroids.shp")
  
Names <- c("Gyttegaard", "Husby", "Trojborg", "Kattrup Vildnis", "Mols", "RyeNorskov")

Contacts <- paste("Contact", 1:length(Names), sep = "_")

labels <- paste(
    "<strong>Names: </strong>", Names,"<br>", "<strong>Contact: </strong>", Contacts,"<br>") %>%
    lapply(htmltools::HTML)


Rewilding <- Paths %>% map2(.y = Names,~SF_TO_POINT_LEAFLET(.x, name = .y)) %>% map2(.y = Contacts,~dplyr::mutate(.x, Contact = .y))%>% purrr::reduce(bind_rows)



Sinks <- read_sf("Samplet_au_sinks_2021/samplede_AU_pkt_2021.shp") %>% st_transform(crs = '+proj=longlat +datum=WGS84')
```


```{r NationalPark}

NationalParks <- list.files(path = "NationalParks/", pattern = ".shp", recursive = T, full.names = T)

NationalNames <- list.dirs(path = "NationalParks/", full.names = F)
NationalNames <- NationalNames[str_detect(NationalNames, pattern = "GIS", negate = T)]

NationalNames <- NationalNames[-1]

NationalParks <- NationalParks %>% 
  purrr::map(read_sf) %>% purrr::map2(.y = NationalNames,~mutate(.x, Name = .y)) %>% purrr::reduce(bind_rows) %>% st_transform(crs = '+proj=longlat +datum=WGS84')
```


```{r}
l <- leaflet() 

esri <- grep("^Esri", providers, value = TRUE)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)
}

l <- l %>%
  addLayersControl(baseGroups = names(esri),
    options = layersControlOptions(collapsed = TRUE),
    overlayGroups = c("Catchment","Rewildling", "Sinks", "National Parks"))  %>%
  htmlwidgets::onRender("
    function(el, x) {
      var myMap = this;
      myMap.on('baselayerchange',
        function (e) {
          myMap.minimap.changeLayer(L.tileLayer.provider(e.name));
        })
    }") %>% 
  addPolygons(data = as_Spatial(st_zm(Areas[[1]])), popup = ~Vandområd, group = "Catchment", weight = 1, color = "#8da0cb",
              highlightOptions = highlightOptions(stroke = 4, weight = 4)) %>%
  addPolygons(data = as_Spatial(st_zm(Areas[[2]])), popup = ~Vandomraad, group = "Sub-Catchment", weight = 1, color = "red",
              highlightOptions = highlightOptions(stroke = 4, weight = 4)) %>%
  addPolygons(data = NationalParks, weight = 1, popup = ~Name, color = "#66c2a5", group = "National Parks") %>% 
  addCircleMarkers(data = Rewilding, group = "Rewildling", popup = ~labels, label = ~labels, color = "#e78ac3") %>% 
  addCircleMarkers(data = Sinks, color = "#fc8d62", group = "Sinks", popup = ~Dato) %>% 
  addLegend(colors = c("#8da0cb","red", "#e78ac3", "#fc8d62", "#66c2a5"), labels = c("Catchment", "ID-15","Rewildling", "Sinks", "Nature National Parks")) %>% 
  addMeasure(position = "topleft", primaryAreaUnit = "sqmeters", secondaryAreaUnit = "hectares", primaryLengthUnit = "meters", thousandsSep = ",") %>% 
  leafem::addMouseCoordinates()

l
```
