---
title: "Spatial Connectivity and its Modeling Consequences"
date: "`r Sys.Date()`"
output: 
    bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Tuesday, February 20th – building 1540 room K20

- 13:00-13:15: Welcome and Round of Presentations
- 13:15-13:45: Derek Corcoran – Package: SpatioTemporalCont – A Simple Way of Generating Continuity Maps for Spatial and Temporal Habitat and Species Suitability [link](https://sustainscapes.github.io/SpatialContinuity/SpatioTemporalCont.html)
- 13:45-14:15: Greta Bocedi – Short introduction: Connectivity in Ecology
- 14:15-14:45: Jesper Bechsgaard – Short introduction: Connectivity and patch sizes in analyses of genetic diversity
- 14:45-15:15: Identifying potential differences in concepts.
- 15:15-16:00: Alignment of Expectations (only Greta, Jesper, Urs, Derek)

## Wednesday, February 21st – building 1223 room 142

- 08:30-09:00: Camila – Modelling the Potential and Actual Distribution of Suitable Habitats
- 09:00-09:30: Oliver Baines/Signe Normand - Using Expert Knowledge to Approximate the Distribution of Suitable Habitats
- 09:30-10:00: Similarities and differences modelling and expert-based approaches.
- 10:00-11:30: Derek Corcoran - Spatial and Temporal Continuity at Different Ecological Levels
  - Theoretical Concepts of Connectivity
  - Continuous Connectivity Approach using Circuit Theory (samc, gDistance, and Circuitscape Approach)
  - Graph-Theoretic Connectivity Analyses (MetaLandSim, and lconnect)
  - Using Network Flow to Study Connectivity Through Time
- 11:30-12:00: Greta Bocedi - Genetic Connectivity in RangeShiftR
- 12:00-13:00: Lunch break
- 13:00-16:00: Parallel or Individual Work Sessions
- 17:30: Common dinner – Aquatic Biology lunch room, building 1135

## Thursday, February 22nd – building 1540 room K20

- 10:30-11:00: Following up on Parallel or Individual Working Sessions
- 11:00-12:00: Using Spatiotemporal GLMMs through Gaussian Markov Random Fields and Meshes to Enhance Spatially Explicit Bayesian Modeling
- 12:00-13:00: Lunch break
- 13:00-16:00: Parallel or Individual Work Sessions

## Friday, February 23rd – building 1540 room K20

- 09:30-10:00: Following up on Parallel or Individual Working Sessions
- 10:00-11:00: Next Steps for Working on Specific Projects

# Workshop Introduction

Welcome to the Spatial Connectivity and its Modeling Consequences Workshop! This workshop aims to explore the diverse facets of spatial connectivity in ecological studies and its modeling implications. Join us for an enriching experience where experts in the field will share their insights, present relevant packages, and engage in discussions to enhance your understanding of spatial connectivity.

# Workshop Requirements

## R Packages

Before attending the workshop, please ensure that you have the following R packages installed:

- `SpatioTemporalCont`: Derek Corcoran's package for generating continuity maps for spatial and temporal habitat and species suitability.

- `RangeShiftR`: Greta Bocedi's package focusing on genetic connectivity.

- Other relevant packages for theoretical concepts and analyses:
  - `samc`
  - `gDistance`
  - `Circuitscape`
  - `MetaLandSim`
  - `lconnect`

## Software Requirements

- R: [Download R](https://cran.r-project.org/mirrors.html)

- RStudio (optional but recommended): [Download RStudio](https://www.rstudio.com/products/rstudio/download/)

Please make sure to install these packages and software tools prior to the workshop to ensure a smooth and productive learning experience. We look forward to your active participation and fruitful discussions during the workshop!

Feel free to reach out if you have any questions or need assistance with the preparations.

See you at the workshop!
