---
title: "Vilhelmsborg"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE)
library(terra)
library(leaflet)
library(leaflet.extras2)
library(leaflet.extras)
library(leaflet.providers)
library(leafpop)
library(dplyr)
library(sf)
library(DT)
library(spThin)

Circle_1000 <- terra::vect("VilhelmsBorg/CircleVilhelm.shp") |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf() |> 
  dplyr::mutate(distance = "1000")

Circle_1500 <- terra::vect("VilhelmsBorg/Circle_1500_Vilhelm.shp") |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf()|> 
  dplyr::mutate(distance = "1500")

Circle_2000 <- terra::vect("VilhelmsBorg/Circle_2000_Vilhelm.shp") |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf()|> 
  dplyr::mutate(distance = "2000")

Circle <- list(Circle_1000, Circle_1500, Circle_2000) |> 
  purrr::reduce(rbind)

Sites <- terra::vect("VilhelmsBorg/Sites.shp")
PrivateSites <- terra::vect("VilhelmsBorg/AllSites.shp")
PrivateSites <- PrivateSites[PrivateSites$Ownership == "Privat",]

Sites <- rbind(Sites, PrivateSites)


Forest_Sites <- terra::vect("VilhelmsBorg/ForestVilhelm_2000.shp")
Private_Forest_Sites <- terra::vect("VilhelmsBorg/ForestVilhelm_All_2000.shp")
Private_Forest_Sites <- Private_Forest_Sites[Private_Forest_Sites$Ownership == "Privat",]

Forest_Sites <- rbind(Forest_Sites, Private_Forest_Sites)



Sites <- Sites |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf() |> 
  dplyr::select(Natyp_navn, Ownership, Status, Area) |> 
  dplyr::mutate(Natyp_navn = stringr::str_replace_all(Natyp_navn,"<f8>", "ø"), Own_nature = paste(Natyp_navn, Ownership))

Forest_Sites <- Forest_Sites |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf() |> 
  dplyr::mutate(Natyp_navn = "Skov", Status = "Unknown") |> 
  dplyr::select(Natyp_navn, Ownership, Status, Area) |> 
  dplyr::mutate(Own_nature = paste(Natyp_navn, Ownership))

Sites <- rbind(Sites, Forest_Sites) %>% mutate(combined_var = paste0(Ownership, "_", Natyp_navn))

Points <-  terra::vect("VilhelmsBorg/SamplingPoints.shp")


Points <- Points |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf()

ForestPoints <- terra::vect("VilhelmsBorg/Forest_points.shp") |> 
  terra::project("+proj=longlat +datum=WGS84") |> 
  sf::st_as_sf() |> 
  dplyr::mutate(ID = readr::parse_number(p25_id))

ForestPoints$PointID <- (1:nrow(ForestPoints) + max(Points$PointID))
  
ForestPoints$Natyp_navn <- "Skov"

ForestPoints <- ForestPoints |> 
  dplyr::select("Natyp_navn", "ID", "PointID")

Points <- rbind(Points, ForestPoints)

mapping_table <- data.frame(
    combined_var = c("Kommunal_Eng", "Privat_Eng", 
"Kommunal_Mose", "Privat_Mose", "Kommunal_Overdrev", "Privat_Overdrev", 
"Kommunal_Sø", "Privat_Sø", "Kommunal_Skov", "Privat_Skov"),
    pal_colour = c("#d53e4f", "#8c0f21", "#fee08b", "#e5b527", 
"#d9d9d9", "#bdbdbd", "#3288bd", "#1e5577", "#7fc97f", "#477b42"),
    stringsAsFactors = FALSE
  )


Pal <- leaflet::colorFactor(palette = mapping_table$pal_colour, 
domain = mapping_table$combined_var, ordered = T)

PalDist <- leaflet::colorFactor(palette = c('#7fc97f','#beaed4','#fdc086'), domain = sort(unique(Circle$distance)))
```

## Generating maps

```{r}
html_string <- '<style>
  .grid-container {
    display: grid;
    grid-template-columns: 53px 53px 53px;
    grid-auto-rows: 27px 27px 27px 27px 27px 27px;
  }

  /* Reduce font size for nature types */
  .nature-types {
    font-size: 11px;
  }
</style>

<div class="grid-container">
  <!-- Categories -->
  <div class="var1-label" style="grid-row: 1; font-size: 11px;">Eng</div>
  <div class="var1-label" style="grid-row: 2; font-size: 11px;">Mose</div>
  <div class="var1-label" style="grid-row: 3; font-size: 11px;">Overdrev</div>
  <div class="var1-label" style="grid-row: 4; font-size: 11px;">Sø</div>
  <div class="var1-label" style="grid-row: 5; font-size: 11px;">Skov</div>

  <!-- Kommunal -->
  <div style="background-color: #d53e4f; color: #d53e4f;">3</div>
  <div style="background-color: #fee08b; color: #fee08b;">6</div>
  <div style="background-color: #d9d9d9; color: #d9d9d9;">9</div>
  <div style="background-color: #3288bd; color: #3288bd;">2</div>
  <div style="background-color: #7fc97f; color: #7fc97f;">5</div>

  <!-- Privat -->
  <div style="background-color: #8c0f21; color: #8c0f21; grid-column: 3; grid-row: 1;">8</div>
  <div style="background-color: #e5b527; color: #e5b527; grid-column: 3; grid-row: 2;">1</div>
  <div style="background-color: #bdbdbd; color: #bdbdbd; grid-column: 3; grid-row: 3;">4</div>
  <div style="background-color: #1e5577; color: #1e5577; grid-column: 3; grid-row: 4;">7</div>
  <div style="background-color: #477b42; color: #477b42; grid-column: 3; grid-row: 5;">6</div>

  <!-- Labels -->
  <div class="nature-types" style="text-align: center; grid-row: 6; grid-column: 2;">Kommunal</div>
  <div class="nature-types" style="text-align: center; grid-row: 6; grid-column: 3;">Privat</div>
</div>'
```


```{r}
ESRI <- c("Esri.WorldImagery", "Esri.WorldStreetMap", "Esri.WorldGrayCanvas")


l <- leaflet() 

for (provider in ESRI) {
  l <- l %>% addProviderTiles(provider, group = provider)
}


l |> addPolylines(data = Circle, weight = 1, color = ~PalDist(distance)) |> addPolygons(data = Sites, color = ~Pal(combined_var), weight = 1, opacity = 0.8, popup = popupTable(Sites)) |> 
  addCircleMarkers(data = Points, popup = popupTable(Points), group = "Points", radius = 3) |> 
  #leaflet::addLegend(data = Sites, "bottomright", pal = Pal, values = ~combined_var,
    #title = "Nature and ownership",
    #opacity = 1,
    #group = "Legend"
  #) 
  leaflet::addControl(html = html_string,
                                                       position = "bottomleft") |>  
  addLayersControl(baseGroups = ESRI,
    overlayGroups = c("Points"),
    options = layersControlOptions(collapsed = FALSE)
  ) |> 
  addMeasure(
    position = "topleft",
    primaryLengthUnit = "meters",
    primaryAreaUnit = "hectares",
    activeColor = "#3D535D",
    completedColor = "#7D4479")|>   addControlGPS(
    options = gpsOptions(
      position = "topleft",
      activate = TRUE, 
      autoCenter = TRUE,
      setView = TRUE)) |> 
leaflet.extras::activateGPS()
```

We can also see a table of all the sites in the following table:

```{r}
Table <- as.data.frame(Sites) |> dplyr::select(-geometry)

DT::datatable(Table)
```