---
title: ""
output:
  rmdformats::robobook:
    highlight: kate
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache = FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(sf)
library(raster)
Points <- read_sf("AllPoints.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") 

Sampled <- Points %>% dplyr::filter(Sampled == "Y")
NonSampled <- Points %>% dplyr::filter(Sampled == "N")


Outline <- read_sf("Kattrup_Vildnis_graense_jan2022.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs")

OpenPairs <- read_sf("OpenPairs.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% mutate(NewLabel = ID_GPX %>% substr(8,12))
```

```{r, out.width= "100%"}

l <-leaflet()
esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]
pal <- colorFactor(
  palette = c('#7fc97f','#beaed4','#fdc086','#ffff99'),
  domain= as.character(sort(unique(Points$Type))),
  ordered = TRUE,
  na.color = "#808080"
)

NewPal <- pal <- colorFactor(
  palette = rainbow(length(unique(OpenPairs$NewLabel))),
  domain= as.character(sort(unique(OpenPairs$NewLabel))),
  ordered = TRUE,
  na.color = "#808080"
)
for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)    
}
l <- l %>% 
    leaflet::addCircleMarkers(data = as_Spatial(Sampled), radius = 6, group = "Sampled", color = ~pal(Type), popup = paste("Code:",Sampled$ID)) %>%
   leaflet::addCircleMarkers(data = as_Spatial(NonSampled), radius = 6, group = "Not sampled", color = ~pal(Type), popup = paste("Code:",NonSampled$ID)) %>%  addPolygons(data = as_Spatial(OpenPairs), group = "New Open pairs", popup = paste("Code:",OpenPairs$ID_GPX), color = ~NewPal(NewLabel)) %>% 
 addPolylines(data = as_Spatial(Outline), color = "blue", fillOpacity = 0, group = "Outline") %>% 
  addLegend("bottomright", pal = pal ,title = "Kattrup sites",opacity = 1, values = unique(Points$Type),  group = "Legend old") %>%
  addLegend("bottomright", pal = NewPal ,title = "Kattrup new open pairs",opacity = 1, values = as.character(sort(unique(OpenPairs$NewLabel))),  group = "Legend New") %>%
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("New Open pairs", "Sampled", "Not sampled", "Legend New","Legend old", "Outline"),
                   options = layersControlOptions(collapsed = TRUE),
                   position = "topright") %>%
  hideGroup("Sampled") %>% 
  hideGroup("Not sampled") %>% 
  hideGroup("Legend old") %>% 
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares") 
  l  %>%
   addControlGPS(
    options = gpsOptions(
      position = "topleft",
      activate = TRUE, 
      autoCenter = TRUE,
      setView = TRUE)) %>% 
  activateGPS()
```