---
title: "Trojborg_interactive"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
library(tidyverse)
library(leaflet)
library(sf)
library(raster)
library(janitor)

Trojborg <- read_sf("GroupsTrojborg.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))


library(readxl)
Trojborg_experimental <- read_excel("Trojborg_experimental_plots.xlsx") %>% 
  st_as_sf(coords = c("long", "lat"),  crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  tidyr::separate(col = point, into = c("Site", "Type", "Env", "ID", "Point", "Point2")) %>% 
  mutate(ID = case_when(is.na(Point2) ~ ID,
                        TRUE ~ Point),
         Point = case_when(is.na(Point2) ~ Point,
                           TRUE ~ Point2)) %>%
  unite("ID", Env:ID) %>% 
  dplyr::select(-Point2) %>%
  dplyr::filter(Point == "C") %>% 
  st_transform(crs = "+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

Squares <- readRDS("ExperimentaSquaresTrojborg.rds") %>% 
  reduce(bind_rows) %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  rename(geometry = x)

BufferCircle <- Trojborg_experimental %>% 
    st_buffer(15) %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  bind_rows(Squares) %>% 
  arrange(ID)
Trojborg_outline <- Trojborg %>% st_union() %>% st_as_sf() %>% st_cast("POLYGON")
```

```{r}
l <-leaflet()

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

pal <- colorFactor(
  palette = c("#9e0142", "#d53e4f", "#fee08b", "#ffffbf", "#66c2a5", "#3288bd"),
  domain= as.character(sort(unique(Trojborg$Group))),
  ordered = TRUE,
  na.color = "#808080"
)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)    
}

l <- l %>% 
  addPolygons(data = as_Spatial(Trojborg), group = "Groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Trojborg$Group, fillOpacity = 0.8) %>%
  addPolylines(data = as_Spatial(BufferCircle), group = "Monitoring",opacity = 1, popup = BufferCircle$ID, fillOpacity = 0.2) %>%
  addPolylines(data = as_Spatial(Trojborg_outline), group = "Outline",opacity = 1, color = "red") %>% 
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("Groups", "Monitoring", "Outline"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares") %>% 
  hideGroup(c("Groups"))

l %>% addLegend("bottomright", pal = pal ,title = "Trojborg sites",opacity = 1, values = Trojborg$Group) %>%
  addEasyButton(easyButton(
    icon="fa-croshairs", title="Locate Me",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))

```
