<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Reproducible research | Reproducible research in R</title>
  <meta name="description" content="A companion book on reproducibility in R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Reproducible research | Reproducible research in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/Cover.png" />
  <meta property="og:description" content="A companion book on reproducibility in R" />
  <meta name="github-repo" content="/derek-corcoran-barrios/derek-corcoran-barrios.github.io/tree/master/Libro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Reproducible research | Reproducible research in R" />
  
  <meta name="twitter:description" content="A companion book on reproducibility in R" />
  <meta name="twitter:image" content="/Cover.png" />

<meta name="author" content="Derek Corcoran" />


<meta name="date" content="2022-02-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tidydata.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Reproducible research in R </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requirements</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#before-starting"><i class="fa fa-check"></i><b>0.1</b> Before starting</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#workshop-description"><i class="fa fa-check"></i><b>0.2</b> Workshop description</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#course-objectives"><i class="fa fa-check"></i><b>0.3</b> Course Objectives</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i><b>0.4</b> Contents</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#libros-de-consulta"><i class="fa fa-check"></i><b>0.5</b> Libros de consulta</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#reference-books"><i class="fa fa-check"></i><b>0.6</b> Reference books</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i><b>0.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tidydata.html"><a href="tidydata.html"><i class="fa fa-check"></i><b>1</b> Tidy Data and data manipulation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="tidydata.html"><a href="tidydata.html#packages-needed-for-this-chapter"><i class="fa fa-check"></i><b>1.1</b> Packages needed for this chapter</a></li>
<li class="chapter" data-level="1.2" data-path="tidydata.html"><a href="tidydata.html#tidy-data"><i class="fa fa-check"></i><b>1.2</b> Tidy data</a></li>
<li class="chapter" data-level="1.3" data-path="tidydata.html"><a href="tidydata.html#dplyr"><i class="fa fa-check"></i><b>1.3</b> dplyr</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="tidydata.html"><a href="tidydata.html#pipeline"><i class="fa fa-check"></i><b>1.3.1</b> Pipeline (%&gt;%)</a></li>
<li class="chapter" data-level="1.3.2" data-path="tidydata.html"><a href="tidydata.html#summarize"><i class="fa fa-check"></i><b>1.3.2</b> summarize</a></li>
<li class="chapter" data-level="1.3.3" data-path="tidydata.html"><a href="tidydata.html#group_by"><i class="fa fa-check"></i><b>1.3.3</b> group_by</a></li>
<li class="chapter" data-level="1.3.4" data-path="tidydata.html"><a href="tidydata.html#mutate"><i class="fa fa-check"></i><b>1.3.4</b> mutate</a></li>
<li class="chapter" data-level="1.3.5" data-path="tidydata.html"><a href="tidydata.html#filter"><i class="fa fa-check"></i><b>1.3.5</b> filter</a></li>
<li class="chapter" data-level="1.3.6" data-path="tidydata.html"><a href="tidydata.html#select"><i class="fa fa-check"></i><b>1.3.6</b> select</a></li>
<li class="chapter" data-level="1.3.7" data-path="tidydata.html"><a href="tidydata.html#exercises"><i class="fa fa-check"></i><b>1.3.7</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reproducible.html"><a href="reproducible.html"><i class="fa fa-check"></i><b>2</b> Reproducible research</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reproducible.html"><a href="reproducible.html#packages-needed-for-this-chapter-1"><i class="fa fa-check"></i><b>2.1</b> Packages needed for this chapter</a></li>
<li class="chapter" data-level="2.2" data-path="reproducible.html"><a href="reproducible.html#reproducible-research"><i class="fa fa-check"></i><b>2.2</b> Reproducible Research</a></li>
<li class="chapter" data-level="2.3" data-path="reproducible.html"><a href="reproducible.html#saving-our-project-on-github"><i class="fa fa-check"></i><b>2.3</b> Saving our project on github</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="reproducible.html"><a href="reproducible.html#what-is-github"><i class="fa fa-check"></i><b>2.3.1</b> What is github?</a></li>
<li class="chapter" data-level="2.3.2" data-path="reproducible.html"><a href="reproducible.html#creating-a-github-project-in-rstudio"><i class="fa fa-check"></i><b>2.3.2</b> creating a github project in RStudio</a></li>
<li class="chapter" data-level="2.3.3" data-path="reproducible.html"><a href="reproducible.html#the-three-main-steps-of-a-repository"><i class="fa fa-check"></i><b>2.3.3</b> The three main steps of a repository</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="reproducible.html"><a href="reproducible.html#reproducibility-in-r"><i class="fa fa-check"></i><b>2.4</b> Reproducibility in R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reproducible.html"><a href="reproducible.html#creating-an-rmarkdown"><i class="fa fa-check"></i><b>2.4.1</b> Creating an Rmarkdown</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible.html"><a href="reproducible.html#subtitle-1"><i class="fa fa-check"></i>subtitle 1</a>
<ul>
<li class="chapter" data-level="" data-path="reproducible.html"><a href="reproducible.html#subtitle-2"><i class="fa fa-check"></i>subtitle 2</a></li>
<li class="chapter" data-level="2.4.2" data-path="reproducible.html"><a href="reproducible.html#training"><i class="fa fa-check"></i><b>2.4.2</b> Training</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Reproducible research in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="reproducible" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Reproducible research</h1>
<div id="packages-needed-for-this-chapter-1" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Packages needed for this chapter</h2>
<p>For this chapter you need to have the <em>rmarkdown</em>, <em>knitr</em>, <em>reprex</em> and <em>kableExtra</em> packages installed.</p>
<p>This chapter will explain what reproducible research is, how to apply it using github plus the <em>rmarkdown</em> <span class="citation">(<a href="#ref-Allaire2018" role="doc-biblioref">Allaire et al. 2018</a>)</span> and <em>knitr</em> <span class="citation">(<a href="#ref-xie2015" role="doc-biblioref">Xie 2015</a>)</span> packages. Also, you will learn how to use tables using <em>knitr</em> <span class="citation">(<a href="#ref-xie2015" role="doc-biblioref">Xie 2015</a>)</span> and <em>kableExtra</em> <span class="citation">(<a href="#ref-Hao2021" role="doc-biblioref">Zhu 2021</a>)</span>. Finally you will learn how use reprex in order to generate reproducible questions in stackoverflow.</p>
<p>This class of the course can also be followed at this <a href="https://sustainscapes.github.io/Class2/Clase2InvestigacionReproducible">link</a>.</p>
</div>
<div id="reproducible-research" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Reproducible Research</h2>
<p>Reproducible research is not the same as replicable research. Replicability implies that experiments or studies carried out under similar conditions will lead to similar conclusions. Reproducible research implies that from the same data and/or the same code the same results will be generated.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:reproducible"></span>
<img src="Reproducible.png" alt="Continuum of reproducibility (extracted from Peng 2011)" width="80%" />
<p class="caption">
Figure 2.1: Continuum of reproducibility (extracted from Peng 2011)
</p>
</div>
<p>In the figure <a href="reproducible.html#fig:reproducible">2.1</a> we see the reproducibility continuum <span class="citation">(<a href="#ref-peng2011reproducible" role="doc-biblioref">Peng 2011</a>)</span>. In this continuum we have the example of non-reproducibility as a post without code. It goes from less reproducible to more reproducible by the publication and the code that generated the results and graphs; followed by the publication, the code and the data that generate the results and graphs; and finally code, data and text intertwined in such a way that when running the code we get exactly the same publication that we read.</p>
<p>This has many advantages, including making it easier to apply the exact same methods to another database. It is enough to put the new database in the format that the author of the first publication had and we can compare the results.</p>
<p>Also, at a time when science is increasingly database-based, data collection and/or sampling can be put into code.</p>
</div>
<div id="saving-our-project-on-github" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Saving our project on github</h2>
<div id="what-is-github" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> What is github?</h3>
<p>Github is a kind of dropbox or google drive designed for reproducible research, where each project is a <em>repository</em>. Most researchers working on reproducible research leave all of their documented work in their repositories, allowing you to interact with other authors.</p>
</div>
<div id="creating-a-github-project-in-rstudio" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> creating a github project in RStudio</h3>
<p>To create a project on github we press <strong>start a project</strong> on the home page of our account, as we see in the figure <a href="reproducible.html#fig:Start">2.2</a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Start"></span>
<img src="StartAProject.png" alt="To start a project on github, you must press Start a project on your home page" width="80%" />
<p class="caption">
Figure 2.2: To start a project on github, you must press Start a project on your home page
</p>
</div>
<p>Then a unique name must be created, and without changing anything else press <strong>create repository</strong> on the green button as we see in the figure <a href="reproducible.html#fig:Name">2.3</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Name"></span>
<img src="NombreRepo.png" alt="Create the name of your repository and press the button create repository" width="80%" />
<p class="caption">
Figure 2.3: Create the name of your repository and press the button create repository
</p>
</div>
<p>This will take you to a page where a url of your new repository will appear as in the figure <a href="reproducible.html#fig:ssh">2.4</a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ssh"></span>
<img src="GitAdress.png" alt="The content of the box that says ssh is the url of your repository" width="80%" />
<p class="caption">
Figure 2.4: The content of the box that says ssh is the url of your repository
</p>
</div>
<p>To incorporate your project into your repository, the first thing you need to do is generate a project in RStudio. For this you must go in the top menu of <em>Rstudio</em> to <em>File &gt; New Project &gt; Git</em> as seen in the figures <a href="reproducible.html#fig:NewProject">2.5</a> and <a href="reproducible.html#fig:NewProject">2.5</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:NewProject"></span>
<img src="NewProject.png" alt="Menu to create a new project" width="80%" />
<p class="caption">
Figure 2.5: Menu to create a new project
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Git"></span>
<img src="Git.png" alt="Select git within the options" width="80%" />
<p class="caption">
Figure 2.6: Select git within the options
</p>
</div>
<p>Then select the location of the new project and paste the url that appears in the figure <a href="reproducible.html#fig:ssh">2.4</a> in the space that says <strong>Repository URL:</strong>, as shown in the figure <a href="reproducible.html#fig:GitRstudio">2.7</a> .</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GitRstudio"></span>
<img src="GitRstudio.png" alt="Paste the repository url into the Repository URL: dialog" width="80%" />
<p class="caption">
Figure 2.7: Paste the repository url into the Repository URL: dialog
</p>
</div>
<p>When your R project is already following the changes on github, a git tab will appear in the upper right window of your RStudio session, as we see in the figure <a href="reproducible.html#fig:GitPan">2.8</a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GitPan"></span>
<img src="GitPan.png" alt="Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha" width="80%" />
<p class="caption">
Figure 2.8: Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha
</p>
</div>
</div>
<div id="the-three-main-steps-of-a-repository" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> The three main steps of a repository</h3>
<p>Github is a whole world, there are many functions and there are experts in the use of github. In this course, we will focus on the 3 main steps of a repository: <em>add</em>, <em>commit</em> and <em>push</em>. To fully understand what each of these steps means, we have to understand that there are two repositories at all times: a local one (on your computer) and a remote one (on github.com). The first two steps <em>add</em> and <em>commit</em> only output changes to your local repository. While <em>push</em> saves the changes to the remote repository.</p>
<div id="git-add" class="section level4" number="2.3.3.1">
<h4><span class="header-section-number">2.3.3.1</span> git add</h4>
<p>This function is what adds files to your local repository. Only these files will be saved on github. Github have a repository size limit of 1 GB and files of 100 MB, since although they give you unlimited repositories, the space of each one is not, particularly in terms of databases. To add a file to your repository you just have to select the files in the git tab. By doing that a green letter A will appear instead of the two yellow question marks, as we see in the figure <a href="reproducible.html#fig:Add">2.9</a>. In this case we only add the file <em>Analisis.r</em> to the repository but not the rest.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Add"></span>
<img src="GitAdd.png" alt="When including your repository in your Rstudio session, the git tab will appear in the upper right window" width="80%" />
<p class="caption">
Figure 2.9: When including your repository in your Rstudio session, the git tab will appear in the upper right window
</p>
</div>
</div>
<div id="git-commit" class="section level4" number="2.3.3.2">
<h4><span class="header-section-number">2.3.3.2</span> git commit</h4>
<p>When you use the <em>commit</em> command you are saving the changes to the files you added to your local repository. To do this in Rstudio, in the same git tab, you must press the <em>commit</em> button as we see in the figure <a href="reproducible.html#fig:Commit">2.10</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Commit"></span>
<img src="Commit.png" alt="To save changes to your repository, press commit in the git tab in the upper right window" width="80%" />
<p class="caption">
Figure 2.10: To save changes to your repository, press commit in the git tab in the upper right window
</p>
</div>
<p>Pressing <em>commit</em> will open a pop-up window, where you will need to write a message describing what you will save. Once I’ve done that, press <em>commit</em> again in the popup as shown in figure <a href="reproducible.html#fig:MessageCommit">2.11</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:MessageCommit"></span>
<img src="MensajeCommit.png" alt="Write a message that remembers the changes you made to the popup" width="80%" />
<p class="caption">
Figure 2.11: Write a message that remembers the changes you made to the popup
</p>
</div>
</div>
<div id="git-push" class="section level4" number="2.3.3.3">
<h4><span class="header-section-number">2.3.3.3</span> git push</h4>
<p>Finally, <em>push</em> will allow you to save changes to your remote repository, which secures your data in the cloud and also makes it available to other researchers. After pressing <em>commit</em> on the popup window (figure <a href="reproducible.html#fig:MessageCommit">2.11</a>), we can press <em>push</em> on the green arrow on the popup window as seen in figure <a href="reproducible.html#fig:push">2.12</a>. Then we will be asked for our username and password, and we can check that our repository is online by entering our github session.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:push"></span>
<img src="Push.png" alt="To save to the remote repository press push on the popup window" width="80%" />
<p class="caption">
Figure 2.12: To save to the remote repository press push on the popup window
</p>
</div>
</div>
</div>
</div>
<div id="reproducibility-in-r" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Reproducibility in R</h2>
<p>There are several packages that allow us to do reproducible research in <code>R</code>, but without a doubt the most relevant are <em>rmarkdown</em> and <em>knitr</em>. Both packages work together when we generate an <em>Rmd</em> (Rmarkdown) file, in which we use text, R code and other elements at the same time to generate a word document, pdf, web page, presentation and/or web application (fig. <a href="reproducible.html#fig:Rmark">2.13</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Rmark"></span>
<img src="Rmark.png" alt="The goal of Rmarkdown is to merge r code with text and data to generate a reproducible document" width="80%" />
<p class="caption">
Figure 2.13: The goal of Rmarkdown is to merge r code with text and data to generate a reproducible document
</p>
</div>
<div id="creating-an-rmarkdown" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Creating an Rmarkdown</h3>
<p>To create an Rmarkdown file, simply go to the menu <em>File &gt; New file &gt; Rmarkdown</em> and with that you will have created a new <em>Rmd</em> file. We will see some of the most typical elements of an Rmarkdown file.</p>
<div id="markdown" class="section level4" number="2.4.1.1">
<h4><span class="header-section-number">2.4.1.1</span> Markdown</h4>
<p>The markdown is the part of the file where we simply write text, although it has some formatting details such as generating bold text, italics, titles and subtitles.</p>
<p>To make text <strong>bold</strong>, it must be between two <code>**bold**</code> asterisks, for text to appear <em>italic</em> it must be between <code>*italic*</code> asterisks. Other examples are the titles of different levels, which are denoted with different numbers of <code>#</code>, as well as the following 4 titles or subtitles:</p>
</div>
</div>
</div>
<div id="subtitle-1" class="section level2 unnumbered">
<h2>subtitle 1</h2>
<div id="subtitle-2" class="section level3 unnumbered">
<h3>subtitle 2</h3>
<div id="subtitle-3" class="section level4 unnumbered">
<h4>subtitle 3</h4>
<div id="subtitle-4" class="section level5 unnumbered">
<h5>subtitle 4</h5>
<p>it would look like this in code</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="reproducible.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## subtitle 1</span></span>
<span id="cb20-2"><a href="reproducible.html#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="reproducible.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="do">### subtitle 2</span></span>
<span id="cb20-4"><a href="reproducible.html#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="reproducible.html#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="do">#### subtitle 3</span></span>
<span id="cb20-6"><a href="reproducible.html#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="reproducible.html#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="do">##### subtitle 4</span></span></code></pre></div>
</div>
</div>
<div id="chunks" class="section level4" number="2.4.1.2">
<h4><span class="header-section-number">2.4.1.2</span> Chunks</h4>
<p>Chunks are one of the most important parts of an Rmarkdown. These are where the code from R (or other programming languages) is added. Which allows the product of our code not to be just a script with pasted results, but actually generated in the same document as our script. The easiest way to add a chunk is by pressing the <em>insert chunk</em> button in Rstudio, this button is located in the upper left window of our RStudio session, as shown in the figure <a href="reproducible.html#fig:Insertchunk">2.14</a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Insertchunk"></span>
<img src="Insertchunk.png" alt="When pressing the insert chunk button, a space will appear in which to insert code" width="80%" />
<p class="caption">
Figure 2.14: When pressing the insert chunk button, a space will appear in which to insert code
</p>
</div>
<p>By pressing this button a space will appear, there you can add a code like the one below, and see the results below.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb21-1"><a href="reproducible.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-2"><a href="reproducible.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="in">library(tidyverse)</span></span>
<span id="cb21-3"><a href="reproducible.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="in">iris %&gt;% group_by(Species) %&gt;% summarize(Petal.Length = mean(Petal.length))</span></span>
<span id="cb21-4"><a href="reproducible.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   Species    Petal.Length
##   &lt;fct&gt;             &lt;dbl&gt;
## 1 setosa             1.46
## 2 versicolor         4.26
## 3 virginica          5.55</code></pre>
<div id="chunk-options" class="section level5" number="2.4.1.2.1">
<h5><span class="header-section-number">2.4.1.2.1</span> Chunk Options</h5>
<p>There are many options for chunks, a complete documentation can be found at the following <a href="https://yihui.name/knitr/options/">link</a>, but here we will show the most common:</p>
<ul>
<li><em>echo</em> = T or F show or not the code, respectively</li>
<li><em>message</em> = T or F displays packet messages, respectively</li>
<li><em>warning</em> = T or F displays warnings, respectively</li>
<li><em>eval</em> = T or F to evaluate or not the code, respectively</li>
<li><em>cache</em> = T or F save or not the result, respectively</li>
</ul>
</div>
</div>
<div id="inline-code" class="section level4" number="2.4.1.3">
<h4><span class="header-section-number">2.4.1.3</span> inline code</h4>
<p>The <em>inline codes</em> are useful to add some value in the text, such as the value of p or the mean. To use it, put a backtick (backsingle quote), r, the code in question and another backtick as follows <code>`r R_code`</code>. We cannot put anything in an <em>inline code</em>, since it can only generate vectors, which often requires a lot of creativity to achieve what we want. For example if we wanted to put the average sepal length of the <code>iris</code> database into an <em>inline code</em> we would put <code>`r mean(iris$Sepal.Length)`</code>, which would result in 5.8433333. As a number with 7 significant figures would look strange in a text, we would also like to use the <code>round</code> function, so that it has 2 significant figures, for that we put the following inline code <code>`r round(mean( iris$Sepal.Length),2)`</code> which returns 5.84. This can be made even more complex if you want to work with a summary table. For example, if we wanted to list the average sepal size we would use <code>summarize</code> from <em>dplyr</em>, but this would result in a data.frame, which doesn’t appear if we try to inline code. Let’s start by seeing how the code would look where we obtained the average size of the sepal.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="reproducible.html#cb23-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="reproducible.html#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="reproducible.html#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(Sepal.Length))</span></code></pre></div>
<p>We would see the result of that code <a href="reproducible.html#tab:SummarySepaltab">2.1</a></p>
<table>
<caption><span id="tab:SummarySepaltab">Table 2.1: </span>Summary of the average length of the sepal of the flowers of the genus Iris.</caption>
<thead>
<tr class="header">
<th align="left">Species</th>
<th align="right">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">setosa</td>
<td align="right">5.006</td>
</tr>
<tr class="even">
<td align="left">versicolor</td>
<td align="right">5.936</td>
</tr>
<tr class="odd">
<td align="left">virginica</td>
<td align="right">6.588</td>
</tr>
</tbody>
</table>
<p>To remove the mean vector from this data frame we could subset it with the <code>$</code> sign. So if we want to output the <em>Mean</em> column of the data frame we created as a vector, we would do the following <code>`r (iris %&gt;% group_by(Species) %&gt;% summarize(Mean = mean(Sepal.Length )))$Mean`</code>. This would output 5.006, 5.936, 6.588.</p>
</div>
</div>
<div id="training" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Training</h3>
<div id="exercise-1-1" class="section level4" number="2.4.2.1">
<h4><span class="header-section-number">2.4.2.1</span> Exercise 1</h4>
<p>Using the <em>iris</em> database, create an inline code that tells the average length of the petal of the species <em>Iris virginica</em></p>
</div>
<div id="tables-in-rmarkdown" class="section level4" number="2.4.2.2">
<h4><span class="header-section-number">2.4.2.2</span> Tables in Rmarkdown</h4>
<p>The most typical function for generating tables in an <em>rmd</em> file is <code>kable</code> from the <em>knitr</em> package, which in its simplest form includes a dataframe as its only argument. In addition to this, we can add some parameters such as <em>caption</em>, which allows us to put a title to the table or <em>row.names</em>, which if put as seen in the code (FALSE) will not show the names of the rows, as seen in the table <a href="reproducible.html#tab:SummaryMeans">2.2</a>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="reproducible.html#cb24-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="reproducible.html#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="reproducible.html#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize_all</span>(mean)</span>
<span id="cb24-4"><a href="reproducible.html#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(DF, <span class="at">caption =</span> <span class="st">&quot;Average per species of all iris database variables.&quot;</span>,</span>
<span id="cb24-5"><a href="reproducible.html#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table>
<caption><span id="tab:SummaryMeans">Table 2.2: </span>Average per species of all iris database variables.</caption>
<thead>
<tr class="header">
<th align="left">Species</th>
<th align="right">Sepal.Length</th>
<th align="right">Sepal.Width</th>
<th align="right">Petal.Length</th>
<th align="right">Petal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">setosa</td>
<td align="right">5.006</td>
<td align="right">3.428</td>
<td align="right">1.462</td>
<td align="right">0.246</td>
</tr>
<tr class="even">
<td align="left">versicolor</td>
<td align="right">5.936</td>
<td align="right">2.770</td>
<td align="right">4.260</td>
<td align="right">1.326</td>
</tr>
<tr class="odd">
<td align="left">virginica</td>
<td align="right">6.588</td>
<td align="right">2.974</td>
<td align="right">5.552</td>
<td align="right">2.026</td>
</tr>
</tbody>
</table>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Allaire, JJ, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng, and Winston Chang. 2018. <em>Rmarkdown: Dynamic Documents for r</em>. <a href="https://CRAN.R-project.org/package=rmarkdown">https://CRAN.R-project.org/package=rmarkdown</a>.
</div>
<div class="csl-entry">
Anderson, Edgar. 1935. <span>“The Irises of the Gaspe Peninsula.”</span> <em>Bulletin of the American Iris Society</em> 59: 2–5.
</div>
<div class="csl-entry">
Henderson, Harold V, and Paul F Velleman. 1981. <span>“Building Multiple Regression Models Interactively.”</span> <em>Biometrics</em>, 391–411.
</div>
<div class="csl-entry">
Kross, Sean, Nick Carchedi, Bill Bauer, and Gina Grdina. 2017. <em>Swirl: Learn r, in r</em>. <a href="https://CRAN.R-project.org/package=swirl">https://CRAN.R-project.org/package=swirl</a>.
</div>
<div class="csl-entry">
Leek, Jeff. 2015. <span>“The Elements of Data Analytic Style.”</span> <em>J. Leek.—Amazon Digital Services, Inc</em>.
</div>
<div class="csl-entry">
Peng, Roger D. 2011. <span>“Reproducible Research in Computational Science.”</span> <em>Science</em> 334 (6060): 1226–27.
</div>
<div class="csl-entry">
R Core Team. 2021. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div class="csl-entry">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2022. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a>.
</div>
<div class="csl-entry">
Wickham, Hadley, and others. 2014. <span>“Tidy Data.”</span> <em>Journal of Statistical Software</em> 59 (10): 1–23.
</div>
<div class="csl-entry">
Xie, Yihui. 2015. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.
</div>
<div class="csl-entry">
Zhu, Hao. 2021. <em>kableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>. <a href="https://CRAN.R-project.org/package=kableExtra">https://CRAN.R-project.org/package=kableExtra</a>.
</div>
</div>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Allaire2018" class="csl-entry">
Allaire, JJ, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng, and Winston Chang. 2018. <em>Rmarkdown: Dynamic Documents for r</em>. <a href="https://CRAN.R-project.org/package=rmarkdown">https://CRAN.R-project.org/package=rmarkdown</a>.
</div>
<div id="ref-peng2011reproducible" class="csl-entry">
Peng, Roger D. 2011. <span>“Reproducible Research in Computational Science.”</span> <em>Science</em> 334 (6060): 1226–27.
</div>
<div id="ref-xie2015" class="csl-entry">
Xie, Yihui. 2015. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.
</div>
<div id="ref-Hao2021" class="csl-entry">
Zhu, Hao. 2021. <em>kableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>. <a href="https://CRAN.R-project.org/package=kableExtra">https://CRAN.R-project.org/package=kableExtra</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tidydata.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Libro.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
