---
title: Using Spatiotemporal GLMMs through Gaussian Markov Random Fields and Meshes to Enhance Spatially Explicit Bayesian Modeling
author: "Derek Corcoran"
date: "`r Sys.Date()`"
output:
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE)
library(SpatioTemporalCont)
library(terra)
library(tidyterra)
library(ggplot2)
library(purrr)
library(sdmTMB)
library(sdmTMB)
library(patchwork)
library(kableExtra)
library(DHARMa)
library(readr)
```

# Problem

## Spatially explicit models

* Spatially explicit models are often not spatially explicit
* Example:

```{r}
Datos <- readr::read_csv("https://raw.githubusercontent.com/derek-corcoran-barrios/derek-corcoran-barrios.github.io/master/Presentaciones_Espacial/Bombus.csv")

B_impatiens <- Datos[Datos$species == "Bombus impatiens",]
## Miremos los datos
Datos <- Datos %>% st_as_sf(coords = c(5, 6), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")
Mapa <- countriesHigh %>% st_as_sf() %>% st_crop(Datos)
```


## Spatially explicit GLMM